---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-site
  labels:
    app: hugo-site
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-site
      tier: frontend
  template:
    metadata:
      labels:
        app: hugo-site
        tier: frontend
    spec:
      containers:
      - name: hugosite
        image: ${REGISTRY_HOST}/hugo-site:v1
        securityContext:
          runAsNonRoot: true
        ports:
        - containerPort: 8080
